version: "{build}"

branches:
  only:
    - master

environment:
  matrix:
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install lerna
  - rm -rf C:\Users\appveyor\AppData\Roaming\npm-cache
  - ./node_modules/.bin/lerna bootstrap -- --force

test_script:
  - ./node_modules/.bin/lerna run unit-test --scope="@bem/sdk.{deps,fs-scheme,walk}"

build: off
